# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-20 22:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a category (e.g. Photography, Cooking, etc.)', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('provider', models.CharField(default='', help_text='Enter name(s) of the service provider', max_length=200)),
                ('about_provider', models.TextField(default='', help_text='Enter a brief introduction of service provider', max_length=1000)),
                ('cost', models.CharField(default='', help_text="Enter service's cost:", max_length=200)),
                ('summary', models.TextField(default='', help_text='Enter a brief description of the service', max_length=1000)),
                ('availability', models.TextField(default='', help_text='Enter your availability', max_length=1000)),
                ('contact', models.EmailField(default='null@gmail.com', help_text="Enter provider's email", max_length=254)),
                ('thumb_photo', models.ImageField(default='holder.js/10s0px280/thumb', help_text='Upload thumbnail image', upload_to='')),
                ('category', models.ManyToManyField(default=None, help_text='Select a category for this service', to='catalog.Category')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introduction', models.CharField(help_text='Tell us about yourself!', max_length=1000)),
                ('has_services', models.BooleanField(default=False, help_text='Does this user have listed services?')),
                ('contact', models.EmailField(default='null@gmail.com', help_text='Enter your email', max_length=254)),
                ('services_offered', models.ManyToManyField(help_text='Select your service(s):', to='catalog.Service')),
                ('user', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
